# Generated by Django 2.2.5 on 2019-09-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20190929_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
