# Generated by Django 2.2.5 on 2019-09-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_game_player_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_player',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
        ),
    ]
