# Generated by Django 2.2.5 on 2019-09-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20190913_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_Player',
            new_name='GamePlayer',
        ),
        migrations.AlterModelTable(
            name='gameplayer',
            table='Game Player Map',
        ),
    ]
