# Generated by Django 2.2.5 on 2019-09-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20190913_1410'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gameplayer',
            table=None,
        ),
    ]
