# Generated by Django 2.2.5 on 2019-09-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20190913_1411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GamePlayer',
            new_name='GamePlayerMap',
        ),
    ]
