# Generated by Django 2.2.5 on 2019-09-14 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20190913_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
    ]
