# Generated by Django 2.2.5 on 2019-10-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20190929_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
            preserve_default=False,
        ),
    ]
