# Generated by Django 2.2.5 on 2019-09-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_auto_20190913_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
