# Generated by Django 2.2.5 on 2019-10-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_auto_20191003_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='approved_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='approved_2',
            field=models.BooleanField(default=False),
        ),
    ]
