# Generated by Django 2.2.5 on 2019-09-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_auto_20190914_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='games',
            field=models.IntegerField(default=0),
        ),
    ]
