# Generated by Django 2.2.5 on 2019-09-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_auto_20190914_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='goal_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='ties',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
